server:
  port: 9071
spring:
  application:
    name: zuul1
  datasource:
    url: jdbc:mysql://116.85.15.199:3306/easymarket?useUnicode=true&characterEncoding=utf8
    username: root
    password:  2wer43@WER$#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  main:
    allow-bean-definition-overriding: true  
eureka: 
  client:
    service-url:
      defaultZone: http://116.85.15.199:9070/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.100.88.59
    instance-id: 47.100.88.59:${server.port}
    hostname:  47.100.88.59
ribbon:
  eureka:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.easyApp.entity
  